version: "3.8"
services:
  # POSTGRESQL
  db:
    build:
      context: docker/postgres
      dockerfile: dockerfile
      args:
        PGDB_NAME: "${PGDB_NAME}"
    restart: "always"
    environment:
      POSTGRES_USER: "${PGDB_USER}"
      POSTGRES_PASSWORD: "${PGDB_PASS}"
    ports:
      - "${PGDB_PORT}:5432"
    volumes:
      - "my_db_data:/var/lib/postgresql/data"

volumes:
  my_db_data:
